apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: runtimevulndetaileds.kubescape.io
spec:
  group: kubescape.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                imageName:
                  type: string
                ancestorName:
                  type: string
                relaventCVEs:
                  type: array
                  items:
                    type: object
                    properties:
                      cVEName:
                        type: string
                      cVESeverity:
                        type: string
                irrelaventCVEs:
                  type: array
                  items:
                    type: object
                    properties:
                      cVEName:
                        type: string
                      cVESeverity:
                        type: string
  names:
    kind: RuntimeVulnDetailed
    plural: runtimevulndetaileds
    singular: runtimevulndetailed
    shortNames:
    - rvd
  scope: Cluster