apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: runtimevulnsummaries.kubescape.io
spec:
  group: kubescape.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                imageName:
                  type: string
                ancestorName:
                  type: string
                summary:
                  type: object
                  properties:
                    imageVulns:
                      type: object
                      properties:  
                        critical:
                          type: integer
                        high:
                          type: integer
                        medium:
                          type: integer
                        low:
                          type: integer
                        negligible:
                          type: integer
                        all:
                          type: integer
                    runtimeVulns:
                      type: object
                      properties:
                        critical:
                          type: integer
                        high:
                          type: integer
                        medium:
                          type: integer
                        low:
                          type: integer
                        negligible:
                          type: integer
                        all:
                          type: integer
                    description:
                      type: string
  scope: Cluster
  names:
    plural: runtimevulnsummaries
    singular: runtimevulnsummary
    kind: RuntimeVulnSummary
    shortNames:
    - rvs
