version: "3"
services:
  postgresql:
    container_name: ovas_postgresql
    image: immauss/openvas:${TAG}
    command: postgresql
    #init: true
    volumes:
      - "openvas:/data"
      - "ovasrun:/run"
    restart: unless-stopped
  mosquitto:
    container_name: ovas_mosquitto
    image: immauss/openvas:${TAG}
    command: mosquitto
    restart: unless-stopped
  notus:
    container_name: ovas_notus
    image: immauss/openvas:${TAG}
    command: notus
    restart: unless-stopped
    volumes:
      - "openvas:/data"
      - "ovasrun:/run"
    depends_on: 
      - "mosquitto" 
  gvmd:
    container_name: ovas_gvmd
    image: immauss/openvas:${TAG}
    command: gvmd
    depends_on: 
      - "postgresql"
    volumes:
      - "openvas:/data"
      - "ovasrun:/run"
    environment:
      - "PASSWORD=admin"
      - "USERNAME=admin"
      - "RELAYHOST=172.17.0.1"
      - "SMTPPORT=25"
      - "QUIET=false"  # dump feed sync noise to /dev/null
      - "SKIPSYNC=true" # Skips the feed sync on startup.
      - "DEBUG=false"  # This will cause the container to stop and not actually start gvmd
      - "GMP=9390"    # to enable see docs
    restart: unless-stopped
  redis:
    container_name: ovas_redis
    image: immauss/openvas:${TAG}
    command: redis
    depends_on:
      - "gvmd"
    volumes: 
      - "ovasrun:/run"
    restart: unless-stopped
  openvas:
    container_name: openvas
    image: immauss/openvas:${TAG}
    init: true
    command: openvas
    depends_on: 
      - "redis"
    volumes:
      - "openvas:/data"
      - "ovasrun:/run"
    restart: unless-stopped
  gsad:
    container_name: ovas_gsad
    image: immauss/openvas:${TAG}
    command: gsad
    depends_on:
      - "gvmd"
    environment:
      - "HTTPS=false"  # wether to use HTTPS or not
    ports:
      - "8080:9392"
    restart: unless-stopped
  scannable:
    image: immauss/scannable
    container_name: ovas_scannable
volumes:
  openvas: 
  ovasrun: 
